//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//azazi//Desktop//GameInitialization//Game//src//ActorGrammar ANTLR//ActorsGrammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ActorsGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IActorsGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ActorsGrammarParser.actorSystem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActorSystem([NotNull] ActorsGrammarParser.ActorSystemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ActorsGrammarParser.actor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActor([NotNull] ActorsGrammarParser.ActorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ActorsGrammarParser.dbwriter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDbwriter([NotNull] ActorsGrammarParser.DbwriterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ActorsGrammarParser.tasknotion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTasknotion([NotNull] ActorsGrammarParser.TasknotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ActorsGrammarParser.keyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyValue([NotNull] ActorsGrammarParser.KeyValueContext context);
}
